version: '3.9'

services:
  backend:
    build:
      context: ./groove
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command:
    
    env_file:
      - .env
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
    depends_on:
      - backend

